AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for EC2 instance running a FastAPI application (Free-tier eligible).

Parameters:
  InstanceType:
    Description: EC2 instance type (free-tier eligible).
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
    ConstraintDescription: Must be a valid EC2 instance type.

  KeyName:
    Description: Name of an existing EC2 KeyPair to allow SSH access.
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  # Security Group for EC2
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to the EC2 instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0

  # EC2 Instance
  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref AppSecurityGroup
      ImageId: ami-09b0a86a2c84101e1
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt update -y
          apt install -y python3 python3-pip git uvicorn redis-server
          # Clone application repository
          git clone https://github.com/binarymachine01/celebrity-finder.git
          cd celebrity-finder
          pip3 install -r requirements.txt
          # Start FastAPI application
          uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload &

Outputs:
  EC2InstancePublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt AppInstance.PublicIp
  EC2InstanceURL:
    Description: URL to access the FastAPI application
    Value: !Sub "http://${AppInstance.PublicIp}:8000/docs"
